# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c "cd backend && golangci-lint run"
        language: system
        types: [go]
        files: ^backend/
      - id: golangci-fmt
        name: golangci-fmt
        entry: bash -c "cd backend && golangci-lint fmt"
        language: system
        types: [go]
        files: ^backend/
      - id: eslint
        name: eslint
        entry: bash -c "cd frontend && yarn lint"
        language: system
        types: [tsx, ts, javascript, jsx]
        files: ^frontend/
      - id: prettier
        name: prettier
        entry: bash -c "cd frontend && yarn format"
        language: system
        types: [tsx, ts, javascript, jsx, json, css, markdown]
        files: ^frontend/
