version: "2"
linters:
  enable:
    - errcheck # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - govet # Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes. [auto-fix]
    - ineffassign # Detects when assignments to existing variables are not used. [fast]
    - staticcheck # It's the set of rules from staticcheck. [auto-fix]
    - unused # Checks Go code for unused constants, variables, functions and types.
