// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dao

import (
	"database/sql"

	null "github.com/guregu/null/v6"
)

type Workflow struct {
	ID          int64        `json:"id"`
	UserID      string       `json:"user_id"`
	Name        string       `json:"name"`
	Description null.String  `json:"description"`
	IsActive    sql.NullBool `json:"is_active"`
	CreatedAt   null.String  `json:"created_at"`
	UpdatedAt   null.String  `json:"updated_at"`
	LastRunAt   null.String  `json:"last_run_at"`
}

type WorkflowEdge struct {
	WorkflowID   int64 `json:"workflow_id"`
	SourceNodeID int64 `json:"source_node_id"`
	TargetNodeID int64 `json:"target_node_id"`
}

type WorkflowNode struct {
	ID         int64       `json:"id"`
	WorkflowID int64       `json:"workflow_id"`
	Name       null.String `json:"name"`
	Type       string      `json:"type"`
	Category   string      `json:"category"`
	Service    null.String `json:"service"`
	Config     string      `json:"config"`
}

type WorkflowNodeUi struct {
	ID         int64       `json:"id"`
	WorkflowID int64       `json:"workflow_id"`
	XPosition  float64     `json:"x_position"`
	YPosition  float64     `json:"y_position"`
	NodeLabel  null.String `json:"node_label"`
	NodeType   string      `json:"node_type"`
}
