// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dao

import (
	null "github.com/guregu/null/v6"
)

type Workflow struct {
	ID          int32       `json:"id"`
	UserID      string      `json:"user_id"`
	Name        string      `json:"name"`
	Description null.String `json:"description"`
	Status      string      `json:"status"`
	CreatedAt   null.Int    `json:"created_at"`
	UpdatedAt   null.Int    `json:"updated_at"`
}

type WorkflowEdge struct {
	WorkflowID   int32 `json:"workflow_id"`
	SourceNodeID int32 `json:"source_node_id"`
	TargetNodeID int32 `json:"target_node_id"`
}

type WorkflowNode struct {
	ID         int32  `json:"id"`
	WorkflowID int32  `json:"workflow_id"`
	ActionType string `json:"action_type"`
	Config     []byte `json:"config"`
}

type WorkflowNodeRun struct {
	ID             int32       `json:"id"`
	WorkflowRunID  int32       `json:"workflow_run_id"`
	WorkflowNodeID int32       `json:"workflow_node_id"`
	Status         string      `json:"status"`
	StartedAt      int64       `json:"started_at"`
	FinishedAt     null.Int    `json:"finished_at"`
	Metadata       []byte      `json:"metadata"`
	ErrorMessage   null.String `json:"error_message"`
	CreatedAt      int64       `json:"created_at"`
	UpdatedAt      int64       `json:"updated_at"`
}

type WorkflowNodeUi struct {
	ID        int32   `json:"id"`
	XPosition float64 `json:"x_position"`
	YPosition float64 `json:"y_position"`
}

type WorkflowRun struct {
	ID         int32    `json:"id"`
	WorkflowID int32    `json:"workflow_id"`
	Status     string   `json:"status"`
	StartedAt  int64    `json:"started_at"`
	FinishedAt null.Int `json:"finished_at"`
	CreatedAt  int64    `json:"created_at"`
	UpdatedAt  int64    `json:"updated_at"`
}

type WorkflowSchedule struct {
	ID             int32    `json:"id"`
	WorkflowID     int32    `json:"workflow_id"`
	ScheduleType   string   `json:"schedule_type"`
	NextRunAt      null.Int `json:"next_run_at"`
	LastRunAt      null.Int `json:"last_run_at"`
	ExecutionState string   `json:"execution_state"`
	CreatedAt      int64    `json:"created_at"`
	UpdatedAt      int64    `json:"updated_at"`
}
