// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: workflow.sql

package dao

import (
	"context"
	"database/sql"

	null "github.com/guregu/null/v6"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflow (
  user_id,
  name,
  description,
  created_at,
  updated_at
)
VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, user_id, name, description, is_active, created_at, updated_at
`

type CreateWorkflowParams struct {
	UserID      string        `json:"user_id"`
	Name        string        `json:"name"`
	Description null.String   `json:"description"`
	CreatedAt   sql.NullInt64 `json:"created_at"`
	UpdatedAt   sql.NullInt64 `json:"updated_at"`
}

// CreateWorkflow
//
//	INSERT INTO workflow (
//	  user_id,
//	  name,
//	  description,
//	  created_at,
//	  updated_at
//	)
//	VALUES (
//	  ?, ?, ?, ?, ?
//	)
//	RETURNING id, user_id, name, description, is_active, created_at, updated_at
func (q *Queries) CreateWorkflow(ctx context.Context, arg *CreateWorkflowParams) (*Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createWorkflowEdge = `-- name: CreateWorkflowEdge :one
INSERT INTO workflow_edge (
  workflow_id,
  source_node_id,
  target_node_id
)
VALUES (
  ?, ?, ?
)
RETURNING workflow_id, source_node_id, target_node_id
`

type CreateWorkflowEdgeParams struct {
	WorkflowID   int64 `json:"workflow_id"`
	SourceNodeID int64 `json:"source_node_id"`
	TargetNodeID int64 `json:"target_node_id"`
}

// CreateWorkflowEdge
//
//	INSERT INTO workflow_edge (
//	  workflow_id,
//	  source_node_id,
//	  target_node_id
//	)
//	VALUES (
//	  ?, ?, ?
//	)
//	RETURNING workflow_id, source_node_id, target_node_id
func (q *Queries) CreateWorkflowEdge(ctx context.Context, arg *CreateWorkflowEdgeParams) (*WorkflowEdge, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowEdge, arg.WorkflowID, arg.SourceNodeID, arg.TargetNodeID)
	var i WorkflowEdge
	err := row.Scan(&i.WorkflowID, &i.SourceNodeID, &i.TargetNodeID)
	return &i, err
}

const createWorkflowNode = `-- name: CreateWorkflowNode :one
INSERT INTO workflow_node (
  workflow_id,
  name,
  type,
  category,
  service,
  config
)
VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, workflow_id, name, type, category, service, config
`

type CreateWorkflowNodeParams struct {
	WorkflowID int64       `json:"workflow_id"`
	Name       null.String `json:"name"`
	Type       string      `json:"type"`
	Category   string      `json:"category"`
	Service    null.String `json:"service"`
	Config     string      `json:"config"`
}

// CreateWorkflowNode
//
//	INSERT INTO workflow_node (
//	  workflow_id,
//	  name,
//	  type,
//	  category,
//	  service,
//	  config
//	)
//	VALUES (
//	  ?, ?, ?, ?, ?, ?
//	)
//	RETURNING id, workflow_id, name, type, category, service, config
func (q *Queries) CreateWorkflowNode(ctx context.Context, arg *CreateWorkflowNodeParams) (*WorkflowNode, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowNode,
		arg.WorkflowID,
		arg.Name,
		arg.Type,
		arg.Category,
		arg.Service,
		arg.Config,
	)
	var i WorkflowNode
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Name,
		&i.Type,
		&i.Category,
		&i.Service,
		&i.Config,
	)
	return &i, err
}

const createWorkflowNodeUi = `-- name: CreateWorkflowNodeUi :one
INSERT INTO workflow_node_ui (
  x_position,
  y_position,
  node_label,
  node_type
)
VALUES (
  ?, ?, ?, ?
)
RETURNING id, x_position, y_position, node_label, node_type
`

type CreateWorkflowNodeUiParams struct {
	XPosition float64     `json:"x_position"`
	YPosition float64     `json:"y_position"`
	NodeLabel null.String `json:"node_label"`
	NodeType  string      `json:"node_type"`
}

// CreateWorkflowNodeUi
//
//	INSERT INTO workflow_node_ui (
//	  x_position,
//	  y_position,
//	  node_label,
//	  node_type
//	)
//	VALUES (
//	  ?, ?, ?, ?
//	)
//	RETURNING id, x_position, y_position, node_label, node_type
func (q *Queries) CreateWorkflowNodeUi(ctx context.Context, arg *CreateWorkflowNodeUiParams) (*WorkflowNodeUi, error) {
	row := q.db.QueryRowContext(ctx, createWorkflowNodeUi,
		arg.XPosition,
		arg.YPosition,
		arg.NodeLabel,
		arg.NodeType,
	)
	var i WorkflowNodeUi
	err := row.Scan(
		&i.ID,
		&i.XPosition,
		&i.YPosition,
		&i.NodeLabel,
		&i.NodeType,
	)
	return &i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, user_id, name, description, is_active, created_at, updated_at
FROM workflow
WHERE id = ?
`

// GetWorkflow
//
//	SELECT id, user_id, name, description, is_active, created_at, updated_at
//	FROM workflow
//	WHERE id = ?
func (q *Queries) GetWorkflow(ctx context.Context, id int64) (*Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getWorkflowEdges = `-- name: GetWorkflowEdges :many
SELECT workflow_id,
  source_node_id,
  target_node_id
FROM workflow_edge
WHERE workflow_id = ?
`

// GetWorkflowEdges
//
//	SELECT workflow_id,
//	  source_node_id,
//	  target_node_id
//	FROM workflow_edge
//	WHERE workflow_id = ?
func (q *Queries) GetWorkflowEdges(ctx context.Context, workflowID int64) ([]*WorkflowEdge, error) {
	rows, err := q.db.QueryContext(ctx, getWorkflowEdges, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowEdge
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(&i.WorkflowID, &i.SourceNodeID, &i.TargetNodeID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowNodes = `-- name: GetWorkflowNodes :many
SELECT id,
  workflow_id,
  name,
  type,
  category,
  service,
  config
FROM workflow_node
WHERE workflow_id = ?
`

// GetWorkflowNodes
//
//	SELECT id,
//	  workflow_id,
//	  name,
//	  type,
//	  category,
//	  service,
//	  config
//	FROM workflow_node
//	WHERE workflow_id = ?
func (q *Queries) GetWorkflowNodes(ctx context.Context, workflowID int64) ([]*WorkflowNode, error) {
	rows, err := q.db.QueryContext(ctx, getWorkflowNodes, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*WorkflowNode
	for rows.Next() {
		var i WorkflowNode
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Name,
			&i.Type,
			&i.Category,
			&i.Service,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
